-- V_MOVIE_ITEM
CREATE OR REPLACE VIEW v_movie_item AS
    SELECT M.NAME, M.YEAR, A.AREA_NAME, TE.TYPE_NAME, TG.TAG_NAME  FROM MOVIE M
        JOIN MOVIE_AREA MA ON M.MOVIE_ID = MA.MOVIE_ID          -- name,year
        JOIN AREA A ON MA.AREA_ID=A.AREA_ID
        JOIN MOVIE_TYPE MTE ON M.MOVIE_ID = MTE.MOVIE_ID        -- type_name
        JOIN TYPE TE ON MTE.TYPE_ID = TE.TYPE_ID
        JOIN MOVIE_TAG MTG ON M.MOVIE_ID = MTG.MOVIE_ID         -- tag_name
        JOIN TAG TG ON MTG.TAG_ID = TG.TAG_ID

-- SELECT
SELECT * FROM v_movie_item;

-- DROP
DROP VIEW V_MOVIE_ITEM;

-- V_MOVIE_SEARCH
CREATE OR REPLACE VIEW v_movie_search AS
    SELECT M.MOVIE_ID,
           M.IMG,
           M.NAME,
           M.YEAR,
           LISTAGG(DISTINCT A.AREA_NAME, ', ') WITHIN GROUP (ORDER BY A.AREA_NAME) AS AREA_NAMES,
           LISTAGG(DISTINCT TE.TYPE_NAME, ', ') WITHIN GROUP (ORDER BY TE.TYPE_NAME) AS TYPE_NAMES,
           LISTAGG(DISTINCT TG.TAG_NAME, ', ') WITHIN GROUP (ORDER BY TG.TAG_NAME) AS TAG_NAMES
    FROM MOVIE M
    JOIN MOVIE_AREA MA ON M.MOVIE_ID = MA.MOVIE_ID
    JOIN AREA A ON MA.AREA_ID = A.AREA_ID
    JOIN MOVIE_TYPE MTE ON M.MOVIE_ID = MTE.MOVIE_ID
    JOIN TYPE TE ON MTE.TYPE_ID = TE.TYPE_ID
    JOIN MOVIE_TAG MTG ON M.MOVIE_ID = MTG.MOVIE_ID
    JOIN TAG TG ON MTG.TAG_ID = TG.TAG_ID
    GROUP BY M.MOVIE_ID, M.IMG, M.NAME, M.YEAR;

-- SELECT
SELECT * FROM v_movie_search;

-- UPDATE
UPDATE MOVIE_LANGUAGE SET LANGUAGE_ID='1' WHERE MOVIE_ID='35505100';


-- V_MOVIE_SEARCH_SON
CREATE OR REPLACE VIEW v_movie_lan AS
    SELECT VMS.MOVIE_ID, VMS.NAME, VMS.YEAR, L.LANGUAGE_NAME
        FROM V_MOVIE_SEARCH VMS
        JOIN MOVIE_LANGUAGE ML ON ML.MOVIE_ID=VMS.MOVIE_ID
        JOIN MOVIE.LANGUAGE L on ML.LANGUAGE_ID = L.LANGUAGE_ID;

-- SELECT
SELECT * FROM V_MOVIE_LAN;

--
SELECT DISTINCT M.MOVIE_ID, M.NAME, M.YEAR, R.RATING, R.COUNTING, A.AREA_NAME, LA.LANGUAGE_NAME,
                AL.ALIAS, LE.LENGTH, TE.TYPE_NAME, TG.TAG_NAME
    FROM MOVIE M
    JOIN RATING R ON M.MOVIE_ID = R.MOVIE_ID
    JOIN MOVIE_AREA MA ON M.MOVIE_ID = MA.MOVIE_ID
    JOIN AREA A ON MA.AREA_ID = A.AREA_ID
    JOIN MOVIE_LANGUAGE MLA ON M.MOVIE_ID = MLA.MOVIE_ID
    JOIN LANGUAGE LA ON MLA.LANGUAGE_ID = LA.LANGUAGE_ID
    JOIN ALIAS AL ON M.MOVIE_ID = AL.MOVIE_ID
    JOIN LENGTH LE ON M.MOVIE_ID = LE.MOVIE_ID
    LEFT JOIN MOVIE_TYPE MTE ON M.MOVIE_ID = MTE.MOVIE_ID
    JOIN TYPE TE ON MTE.TYPE_ID = TE.TYPE_ID
    JOIN MOVIE_TAG MTG ON M.MOVIE_ID = MTG.MOVIE_ID
    JOIN TAG TG ON MTG.TAG_ID = TG.TAG_ID;


