-- PRIMARY_TABLE
-- MOVIE
-- get_year
SELECT M.NAME, M.YEAR
FROM MOVIE M
WHERE M.YEAR=2022
ORDER BY M.YEAR DESC;

-- get_website
SELECT M.NAME, M.WEBSITE
FROM MOVIE M
WHERE M.WEBSITE IS NOT NULL;

-- PERSONAGE
-- get_gender
SELECT P.NAME, P.GENDER, P.FN_NAME
FROM PERSONAGE P
WHERE P.GENDER='女' and P.FN_NAME IS NOT NULL;

-- get_fans_count
SELECT P.NAME, P.BIRTH, P.FANS_COUNT
FROM PERSONAGE P
WHERE P.DEATH IS NULL
ORDER BY P.FANS_COUNT DESC;

-- get_not_imdb
SELECT P.NAME, P.CN_NAME, P.BIRTH_AREA, P.IMDB
FROM PERSONAGE P
WHERE P.IMDB IS NULL;

-- get_auteur/get_scriptwriter/get_actor
SELECT M.NAME,
       LISTAGG(DISTINCT P.NAME, ', ') WITHIN GROUP (ORDER BY P.NAME) AS ACTOR
FROM MOVIE M
JOIN MOVIE_PERSONAGE MP ON M.MOVIE_ID = MP.MOVIE_ID
JOIN PERSONAGE P ON MP.PERSONAGE_ID = P.PERSONAGE_ID
WHERE MP.ACTOR=1  -- get_movie：AND M.MOVIE_ID = 27119724
GROUP BY M.NAME;


-- N:M
-- TYPE
-- get_tag
SELECT TG.TAG_NAME
FROM TAG TG
JOIN TYPE_TAG TT ON TG.TAG_ID = TT.TAG_ID
JOIN TYPE TE ON TT.TYPE_ID = TE.TYPE_ID
WHERE TYPE_NAME = '喜剧';

-- get_movie
SELECT M.NAME, M.YEAR, M.IMDB
FROM MOVIE M
JOIN MOVIE_TYPE MTE ON M.MOVIE_ID = MTE.MOVIE_ID
JOIN TYPE TE ON TE.TYPE_ID = MTE.TYPE_ID
WHERE TYPE_NAME = '科幻';

-- TAG
-- get_type
SELECT TE.TYPE_NAME
FROM TYPE TE
JOIN TYPE_TAG TT ON TE.TYPE_ID = TT.TYPE_ID
JOIN TAG TG ON TT.TAG_ID = TG.TAG_ID
WHERE TAG_NAME = '喜剧';

-- get_movie
SELECT M.NAME, M.YEAR
FROM MOVIE M
JOIN MOVIE_TAG MTG ON M.MOVIE_ID = MTG.MOVIE_ID
JOIN TAG TE ON TE.TAG_ID = MTG.TAG_ID
WHERE TAG_NAME = '剧情'
ORDER BY M.YEAR DESC;

-- AREA
-- get_area
SELECT M.NAME, M.YEAR, A.AREA_NAME
FROM MOVIE M
JOIN MOVIE_AREA MA ON M.MOVIE_ID = MA.MOVIE_ID
JOIN AREA A ON MA.AREA_ID = A.AREA_ID
WHERE A.AREA_NAME='英国';

-- LANGUAGE
SELECT M.NAME, M.YEAR, L.LANGUAGE_NAME
FROM MOVIE M
JOIN MOVIE_LANGUAGE ML ON M.MOVIE_ID = ML.MOVIE_ID
JOIN LANGUAGE L ON ML.LANGUAGE_ID = L.LANGUAGE_ID
WHERE L.LANGUAGE_NAME = '粤语';


-- 1:N
-- RELEASE
-- get_release
SELECT M.NAME,
       LISTAGG(DISTINCT R.RELEASE, '/') WITHIN GROUP (ORDER BY R.RELEASE DESC) AS RELEASES
FROM MOVIE M
JOIN RELEASE R ON M.MOVIE_ID = R.MOVIE_ID
group by M.NAME;

-- get_MOST_RECENT_RELEASE
SELECT M.NAME,
       MAX(SUBSTR(R.RELEASE, 1, 10)) AS MOST_RECENT_RELEASE
FROM MOVIE M
JOIN RELEASE R ON M.MOVIE_ID = R.MOVIE_ID
GROUP BY M.NAME
ORDER BY MOST_RECENT_RELEASE DESC;

-- LENGTH
-- get_length
SELECT M.NAME,
    LISTAGG(DISTINCT L.LENGTH, ', ') WITHIN GROUP (ORDER BY L.LENGTH) AS ACTOR
FROM MOVIE M
JOIN LENGTH L ON M.MOVIE_ID = L.MOVIE_ID
group by M.NAME
HAVING COUNT(DISTINCT L.LENGTH) > 1;  --查询L.LENGTH条数大于1

-- ALIAS
SELECT M.NAME, A.ALIAS
FROM MOVIE M
JOIN ALIAS A ON M.MOVIE_ID = A.MOVIE_ID
WHERE A.ALIAS='古鲁家族2：霸器新時代(港)';

-- 1:1
-- RATING
-- get_rating
SELECT M.NAME, R.RATING,R.COUNTING,R.CONTRAST
FROM MOVIE M
JOIN RATING R ON R.MOVIE_ID = M.MOVIE_ID
WHERE R.RATING>=8
ORDER BY R.RATING DESC;

-- ELSE
SELECT * FROM MOVIE;

SELECT * FROM PERSONAGE;

SELECT MOVIE_ID || ' 电影的 ' || NAME AS "电影编号 名称"
    FROM MOVIE;

SELECT
    m.name AS movie_name,
    m.year AS release_year,
    m.imdb AS imdb_number,
    (SELECT COUNT(*)
     FROM MOVIE_PERSONAGE mp
     WHERE mp.movie_id = m.movie_id) AS character_count
FROM
    MOVIE m;

SELECT
    m.name AS movie_name,
    m.year AS release_year,
    m.imdb AS imdb_number,
    (SELECT LISTAGG(t.type_name, ', ') WITHIN GROUP (ORDER BY t.type_name)
         FROM MOVIE_TYPE mt
         JOIN TYPE t ON mt.type_id = t.type_id
         WHERE mt.movie_id = m.movie_id) AS movie_types
FROM
    MOVIE m;

